### ISSUE TITLE
Not able to upgrade engine-munger(version 1.1.1)

### ISSUE THREAD

**Issue by mailto-kkk** [krakenjs/engine-munger#44]
Hi,

I am using the node version of 5.3.0.
I am trying to upgrade the below module.

```
 I. engine-munger from the version 0.2.8 to 1.1.1
```

II. adarois from the version 0.1.10 to 1.0.1
III. dustjs-linkedin from the version 2.6.2 to 2.7.2
when I give the command "npm install", it is giving the below error message

```
Unhandled rejection Error: Cannot find module 'engine-munger/lib/expressView'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
```

Can you please provide some suggestions?

@lmarkus

**Comment by aredridel** [comment]
What is giving this error message? That's not the kind of error that `npm install` will give.

however, `engine-munger` 1.x has a different API and scope than 0.1.x did. You can't just upgrade it with no change. It does different things for different reasons. You may want to use `adaro` directly, or look into using the `makara` module to wrap things up in a kraken shaped package.

**Comment by lmarkus** [comment]
Since you're upgrading... Just to make sure, did you actually clean your `node_modules` folder and re-install?

**Comment by aredridel** [comment]
That shouldn't be needed.

**Comment by grawk** [comment]
Closing due to inactivity

**Comment by sreenivasulun** [comment]
I am facing the same issue now. As @aredridel  said I am planning to upgrade to makara as per instructions given in link  [Upgrading to Makara 2!](http://krakenjs.com/2015/07/09/upgrading-makara.html) . I am also fine if can upgrade engine-munger to latest version. After I try, I will come back again. Meanwhile if anybody has solution already, please help me. 
I am using nodejs 8.1.4 .
Thank you!
